export const config = {
  cardsItem: '.cards__item',
  cardsTitle: '.cards__title',
  cardsImage: '.cards__image',
  cardsLike: '.cards__like',
  cardsTrash: '.cards__trash',
  cardsLikeActive: 'cards__like_active',
  formSelector: '.form',
  inputSelector: '.popup__input',
  submitButtonSelector: '.popup__save',
  inactiveButtonClass: 'popup__save_type_inactive',
  inputErrorClass: 'popup__input_type_error',
  errorClass: 'popup__input-error_active',
  popupImage: '.popup__picture',
  popupTitleImage: '.popup__title_type_image',
  popupTypeImage: '.popup_type_image',
  popupEditProfile: '.popup_type_edit-profile',
  formTypeEditProfile: '.popup__container_type_edit-profile',
  formTypeAddCard: '.popup__container_type_add',
  popupTypeAddCard: '.popup_type_add',
  profileName: '.profile__name',
  profileJob: '.profile__about-me',
  profileAvatar: '.profile__image',
  popupDeleteCard: '.popup_type_trash',
  cardsLikeCounter: '.cards__count-like',
  popupEditAvatar: '.popup_type_edit-avatar'
}

